# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: b6df5ce52bbc63
  password: f82ebc5b
  host: localhost

development:
  <<: *default
  database: editor_development

test:
  <<: *default
  database: editor_test

production:
  <<: *default
  database: heroku_ec7331b11c15f13%
  host: us-cdbr-iron-east-05.cleardb.net