# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root

development:
  <<: *default
  database: editor_development

test:
  <<: *default
  database: editor_test

production:
  <<: *default
  username: b8e0524ab37617
  password: 67635a3a
  database: heroku_6c43b6c53e9ecf8%
  host: us-cdbr-iron-east-05.cleardb.net